[package]
name = "x07-contracts"
version = "0.1.43"





















































































































edition = "2021"

[dependencies]
