[package]
name = "x07-contracts"
version = "0.1.45"























































































































edition = "2021"

[dependencies]
