[package]
name = "x07-contracts"
version = "0.1.46"
























































































































edition = "2021"

[dependencies]
