[package]
name = "x07-proc-echo"
version = "0.1.38"
















































































































edition = "2021"
publish = false

[dependencies]
