[package]
name = "x07-proc-echo"
version = "0.1.25"



































































































edition = "2021"
publish = false

[dependencies]
