[package]
name = "x07-ext-fs-native"
version = "0.0.41"

















edition = "2021"
license = "Apache-2.0 OR MIT"

[lib]
name = "x07_ext_fs"
crate-type = ["staticlib"]
test = false
doctest = false

[dependencies]
globset = "0.4.14"
once_cell = "1.19.0"
walkdir = "2.5.0"
