[package]
name = "x07-ext-stdio-native"
version = "0.1.38"


























edition = "2021"
license = "Apache-2.0 OR MIT"

[lib]
name = "x07_ext_stdio"
crate-type = ["staticlib", "rlib"]
doctest = false

[dependencies]

