[package]
name = "x07-proc-worker-frame-echo"
version = "0.1.24"


































































































edition = "2021"
publish = false

[dependencies]
