[package]
name = "x07-runner-common"
version = "0.0.69"






































edition = "2021"

[dependencies]
anyhow = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

x07-contracts = { path = "../x07-contracts" }
